#ifndef __COLORS_H__
#define __COLORS_H__

#define CRESET              "[0m"
#define CCLEAR              "[2J"
#define CFG_BLACK           "[2;30m"
#define CFG_RED             "[2;31m"
#define CFG_GREEN           "[2;32m"
#define CFG_YELLOW          "[2;33m"
#define CFG_BLUE            "[2;34m"
#define CFG_MAGENTA         "[2;35m"
#define CFG_CYAN            "[2;36m"
#define CFG_WHITE           "[2;37m"
#define CFG_BRIGHT_BLACK    "[1;30m"
#define CFG_BRIGHT_RED      "[1;31m"
#define CFG_BRIGHT_GREEN    "[1;32m"
#define CFG_BRIGHT_YELLOW   "[1;33m"
#define CFG_BRIGHT_BLUE     "[1;34m"
#define CFG_BRIGHT_MAGENTA  "[1;35m"
#define CFG_BRIGHT_CYAN     "[1;36m"
#define CFG_BRIGHT_WHITE    "[1;37m"
#define CBG_BLACK           "[24;40m"
#define CBG_RED             "[24;41m"
#define CBG_GREEN           "[24;42m"
#define CBG_YELLOW          "[24;43m"
#define CBG_BLUE            "[24;44m"
#define CBG_MAGENTA         "[24;45m"
#define CBG_CYAN            "[24;46m"
#define CBG_WHITE           "[24;47m"
#define CBG_BRIGHT_BLACK    "[4;40m"
#define CBG_BRIGHT_RED      "[4;41m"
#define CBG_BRIGHT_GREEN    "[4;42m"
#define CBG_BRIGHT_YELLOW   "[4;43m"
#define CBG_BRIGHT_BLUE     "[4;44m"
#define CBG_BRIGHT_MAGENTA  "[4;45m"
#define CBG_BRIGHT_CYAN     "[4;46m"
#define CBG_BRIGHT_WHITE    "[4;47m"

#endif